-- AlterTable
ALTER TABLE "SubTask" ALTER COLUMN "startAt" SET DATA TYPE TEXT,
ALTER COLUMN "endAt" SET DATA TYPE TEXT;

-- AlterTable
ALTER TABLE "Task" ALTER COLUMN "startAt" SET DATA TYPE TEXT,
ALTER COLUMN "endAt" SET DATA TYPE TEXT;
